### ISSUE TITLE
【Bugs】上传图片的时候有bug，直接报错

### ISSUE THREAD

**Issue by white0dew** [aifuxi/fuxiaochen#49]
报错如下：rror: ENOENT: no such file or directory, open '/var/task/public/uploads/08ba6742be764c5d92a1cc6d9ab8c464~tplv-5jbd59dj06-image-ji7apjz4z12uxl36y0bnautb.png'
    at Object.openSync (node:fs:561:18)
    at Object.writeFileSync (node:fs:2358:35)
    at C (/var/task/.next/server/chunks/3300.js:5:17009)
    at async N (/var/task/.next/server/chunks/3300.js:5:18287)
    at async /var/task/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rE (/var/task/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
    at async r7 (/var/task/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
    at async es (/var/task/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25916)
    at async en.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1026)
    at async r6.renderToResponseWithComponentsImpl (/var/task/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:508) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/task/public/uploads/08ba6742be764c5d92a1cc6d9ab8c464~tplv-5jbd59dj06-image-ji7apjz4z12uxl36y0bnautb.png',
  digest: '3288304805'
}
从代码上来看，是没有成功在vercel上读取对应的文件

**Comment by aifuxi** [comment]
我猜可能有以下2点原因：
1. 部署到Vercel上的话好像是不能直接使用node里面的fs相关的api的，因为Vercel的部署环境应该算是一个Edge环境，有限制。
2. 还有就是你每次在Vercel重新部署项目，其实算是”重新换了一台机器“，代码运行的环境是在另一个文件夹内运行的，之前上传的文件就会不存在了。

使用自己的云服务器部署我没有遇到过这个问题

**Comment by white0dew** [comment]
感谢解答，猜测就是这个原因，我自己部署在服务器之后就没有这个问题了。另外，xiaochen你有试过nextjs的资源cdn化吗？就是将静态资源自动上传到cdn而不是在服务器上

**Comment by aifuxi** [comment]
> 感谢解答，猜测就是这个原因，我自己部署在服务器之后就没有这个问题了。另外，xiaochen你有试过nextjs的资源cdn化吗？就是将静态资源自动上传到cdn而不是在服务器上

对于现在这个项目来说是不可以的，因为很多页面是动态生成的不是写死的；cdn上一般是那种不会变化的文件才考虑放到上面。文章内的图片这种资源我是上传到阿里的OSS上的
